### ISSUE TITLE
Zoom on a specific 3DTiles Layer

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#176] opened 2021-06-02 15:51 UTC
In order to visualize a 3DTiles layer that is not currently visible (i.e not in the field of view), there is a need to be able to move camera on it using the extent of the 3DTiles layer.
 
This functionality would help to debug 3dtiles.

**Comment by clementcolin** [comment] 2021-06-24 07:21
Before solving this issue, there is a need to fix the extent and bounding box of incoming 3DTiles, created with py3dtiles.

**Comment by clementcolin** [comment] 2021-06-24 15:31
Wrong bounding box calculation was fixed in [this PR](https://github.com/VCityTeam/py3dtiles/pull/13), this issue can now be fixed

**Comment by EricBoix** [comment] 2021-07-05 10:07
Duplicate of [issue 146](https://github.com/VCityTeam/UD-Viz/issues/146).
Closing.

**Closed by EricBoix** 2021-07-05 10:07 UTC
