### ISSUE TITLE
Provide simple means to place a World Object within an iTowns scene

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#263] opened 2021-11-26 10:37 UTC
iTowns knows how to transpose a World Object (described through an `OBJ` file) to the a scene representing
the geographic scene (described in the RGF93 CC46 projection system).
It does so, behind the "scene", through calls e.g like  
```javascript
itowns.View.prototype.addLayer.call(view, $3dTilesLayer).then(layerGeom =>
                layerGeom.object3d.children
       );
```
where [addLayer() is defined here](https://github.com/iTowns/itowns/blob/09e047adf8a8e7604819d8b63fafaf41f906dfc8/src/Core/View.js#L314).

**Comment by DiegoVinasco** [comment] 2023-01-09 13:36
closing, duplicate of #260

**Closed by DiegoVinasco** 2023-01-09 13:36 UTC
Labels: duplicate, enhancement, priority-low
