### ISSUE TITLE
[Temporal Module] Implementation not compliant with the temporal extension

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Viz#152] opened 2020-10-31 18:00 UTC
The implementation of the 3D Tiles temporal extension is not compliant with the last version of the extension (only minor differences). For instance, the transactions types are not the same. This should be updated server side first (in Py3DTiles) to create tilesets compliant with the extension that could then be loaded in UD-Viz.

Once this is done, one area of improvement would be to use the json schemas of the temporal extension to verify the integrity of the parsed extension.

**Comment by valentinMachado** [comment] 2023-04-18 16:43
Actually doing a runtime check based on the jsonSchemas sounds the right way of checking 3DTiles metadata (so the schemas is not duplicated in .json and in javascript code). Since the tileset.json contains the json schemas url we could after fetching tileset fetch these schema then perform the check.

Do we want to loose performance over robustness ? (since this method require another .json request but should only fetch a few ko)
This method to check 3DTiles metadata could be contributed directly in itowns ?

WDYT ? @jailln

**Comment by valentinMachado** [comment] 2023-04-18 17:14
Actually I see here a good way to get rid of the extension class of itowns, so I don't see it as an option but as the way of validating metadata in 3DTiles.
Since we could implement a generic parser validating javascript pur data object based on a json schema.
As you said we should first measure the performance impact but I am not that concern about it since the size of this json schema should be very small compare to the .b3dm also fetched.

For me the problem is more that by doing that we make the 3DTiles itowns pipeline dependant of another external resource (the server hosting this json schema) in addition of the one hosting 3DTiles...

**Comment by jailln** [comment] 2023-04-18 17:19
Oh ok you meant only for the extensions, I thought you meant also for all the 3D Tiles classes.

> For me the problem is more that by doing that we make the 3DTiles itowns pipeline dependant of another external resource (the server hosting this json schema) in addition of the one hosting 3DTiles...

Yes I agree with you, and I think this can be a big issue. Also, are you sure that the json schema is always in the tileset.json? For instance, [this dataset](https://raw.githubusercontent.com/AnalyticalGraphicsInc/cesium/master/Apps/SampleData/Cesium3DTiles/Hierarchy/BatchTableHierarchy/tileset.json) (given by cesium as an example dataset) uses an extension but does not link its json schema.

**Comment by valentinMachado** [comment] 2023-04-18 17:43
> Oh ok you meant only for the extensions, I thought you meant also for all the 3D Tiles classes.

It could also be used for 3DTiles specs so the javascript code would always be up to date with the current 3DTiles implementation but this should not change often, so for me the real benefit would be to use this when an user of 3DTiles creates an extension. The json schemas is the feature proposed by Cesium to describe a data structure (from what I've understood) as a lazy person I don't want to do thing twice so I want to make a validating system based on this schemas (which is the solution I rather since it looks like the convention here) or I don't want to use these schemas at all and do it in pur javascript style...    

> 
> > For me the problem is more that by doing that we make the 3DTiles itowns pipeline dependant of another external resource (the server hosting this json schema) in addition of the one hosting 3DTiles...
> 
> Yes I agree with you, and I think this can be a big issue. Also, are you sure that the json schema is always in the tileset.json? For instance, [this dataset](https://raw.githubusercontent.com/AnalyticalGraphicsInc/cesium/master/Apps/SampleData/Cesium3DTiles/Hierarchy/BatchTableHierarchy/tileset.json) (given by cesium as an example dataset) uses an extension but does not link its json schema.

Maybe this jsonSchema check could be optional :
- if the json schema is not provided there is no validation check and we just hope the user knows what he is doing (like in js lol)
- if the server hosting the schema is down a timeout/failed request is handle by the code

**Comment by jailln** [comment] 2023-04-19 07:16
> It could also be used for 3DTiles specs so the javascript code would always be up to date with the current 3DTiles implementation but this should not change often, so for me the real benefit would be to use this when an user of 3DTiles creates an extension. The json schemas is the feature proposed by Cesium to describe a data structure (from what I've understood) as a lazy person I don't want to do thing twice so I want to make a validating system based on this schemas (which is the solution I rather since it looks like the convention here) or I don't want to use these schemas at all and do it in pur javascript style...

For the 3DTiles core spec it would still allow to detect potential errors in loaded 3DTiles and inform users that their 3D Tiles is not standard which may sometimes explain why it is not rendered. The only tricky thing is that in the early days of 3D Tiles, it was not a standard and it was still evolving while also already being used so there is some (many) 3D Tiles datasets in these alternatives pre-1.0 3D Tiles version for which there is no json schema :grin: Anyway we could still validate them and throw a warning indicating that the 3D Tiles loaded is not standard.

> Maybe this jsonSchema check could be optional :
> 
> * if the json schema is not provided there is no validation check and we just hope the user knows what he is doing (like in js lol)
> * if the server hosting the schema is down a timeout/failed request is handle by the code
> 
> If this check is optional as you said we should let the possibility to activate it or not.

Yes I agree with you, it should be optional. It would not allow to get rid of the 3d tiles extension mechanism in itowns but it would at least validate the 3D Tiles extensions chunk loaded against a schema and improve error detection.

**Comment by valentinMachado** [comment] 2023-05-02 15:41
Should I close this and open an issue in itowns ? or directly propose a PR to itowns ?

**Comment by jailln** [comment] 2023-05-02 15:43
I think you should close this and open an issue in itowns

**Comment by valentinMachado** [comment] 2023-05-02 15:57
[done](https://github.com/iTowns/itowns/issues/2090)

**Closed by valentinMachado** 2023-05-02 15:57 UTC
Labels: priority-high, component@temporal
